<?php

namespace Database\Seeders;

use App\Models\EventCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    protected function generateRandomString($length = 5) {
        $characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    public function run(): void
    {
        $t_event = array(
            array(
                "id" => 4,
                "title" => "Vaksinasi Januari Minggu 1",
                "sub_desc" => "",
                "description" => "RSUD Cimacan membuka pelayanan Vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 3 sampai 7 Januari 2022.<br /><br />Kami menyediakan Vaksin jenis Sinovac untuk dosis 1 dan 2.<br /><br />Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, dan membawa alat tulis pribadi (ballpaint).<br /><br />Yuk Sahabat Cimacan vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105111643_vaksinasi_januari_1.jpg",
                "start_date" => "2022-01-03",
                "end_date" => "2022-01-07",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:16:44",
                "update_date" => "2022-01-05 11:16:44",
            ),
            array(
                "id" => 5,
                "title" => "Vaksinasi Desember Minggu 4",
                "sub_desc" => "",
                "description" => "RSUD Cimacan membuka pelayanan Vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 27 hingga 31 Desember 2021.<br /><br />Kami menyediakan Vaksin jenis Sinovac dan Astrazeneca untuk dosis 1 dan 2.<br /><br />Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, dan membawa alat tulis pribadi (ballpaint).<br /><br />Yuk Sahabat Cimacan vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105111949_vaksinasi_desember_4.jpg",
                "start_date" => "2021-12-27",
                "end_date" => "2021-12-31",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:19:49",
                "update_date" => "2022-01-05 11:19:49",
            ),
            array(
                "id" => 6,
                "title" => "Vaksinasi Desember Minggu 3",
                "sub_desc" => "",
                "description" => "RSUD Cimacan membuka pelayanan Vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 20 hingga 24 Desember 2021.<br /><br />Kami menyediakan Vaksin jenis Astrazeneca untuk dosis 1 dan 2 serta Vaksin Pfizer dan Sinovac untuk dosis ke-2.<br /><br />Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, dan membawa alat tulis pribadi (ballpaint).<br /><br />Yuk kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105112211_vaksinasi_desember_3.jpg",
                "start_date" => "2021-12-20",
                "end_date" => "2021-12-24",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:22:11",
                "update_date" => "2022-01-05 11:22:11",
            ),
            array(
                "id" => 7,
                "title" => "Vaksinasi Desember Minggu 2",
                "sub_desc" => "",
                "description" => "RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 13 hingga 17 Desember 2021.<br /><br />Kami menyediakan Vaksin jenis Pfizer dan Sinovac untuk dosis 2 serta Vaksin Astrazeneca untuk dosis 1 dan 2.<br /><br />Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk Sahabat Cimacan vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105112434_vaksinasi_desember_2.jpg",
                "start_date" => "2021-12-13",
                "end_date" => "2021-12-17",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:24:34",
                "update_date" => "2022-01-05 11:24:34",
            ),
            array(
                "id" => 8,
                "title" => "IG Live Serumen Telinga Bahaya atau Tidak",
                "sub_desc" => "",
                "description" => "Halo Sahabat Cimacan..<br />Mincan mau memberikan info menarik yang ditunggu-tunggu Sahabat Cimacan semua nih!<br /><br />Pada kesempatan kali ini, kita akan membahas mengenai kotoran (serumen) telinga dan serba-serbi yang perlu diketahui untuk menjaga kesehatan telinga.<br /><br />Banyak Sahabat Cimacan yang menanyakan bagaimana cara terbaik untuk menjaga kesehatan telinga kita, bagaimana cara membersihkan telinga yang benar, dan apakah boleh kita mengorek telinga menggunakan cotton bud?<br /><br />Nah, bagi Sahabat Cimacan yang ingin mengetahui lebih lanjut mengenai serumen telinga dan bagaimana cara menjaga kebersihan telinga, yuk simak dan ketahui lebih lanjut dengan bergabung dalam live Instagram bersama dr. Pudyastuti Rachyanti, Sp.THT-KL&nbsp;<a class=\"notranslate\" tabindex=\"0\" href=\"https://www.instagram.com/kiki_prima/\">@kiki_prima</a>&nbsp;dan host Ary Sunjaya&nbsp;<a class=\"notranslate\" tabindex=\"0\" href=\"https://www.instagram.com/rysoen87/\">@rysoen87</a><br /><br />Live Instagram akan berlangsung pada:<br />Kamis, 9 Desember 2021<br />Pukul 13.00 WIB<br /><br />Jangan sampai ketinggalan yaa!<br />Follow akun resmi RSUD Cimacan di&nbsp;<a class=\"notranslate\" tabindex=\"0\" href=\"https://www.instagram.com/rsud_cimacan/\">@rsud_cimacan</a><br /><br />Siapkan pertanyaan kalian yaa Sahabat Cimacan agar dapat ditanyakan langsung pada saat live dengan cara ketik di kolom komentar.",
                "category" => "EcP6WsMO5hq7aHje1YoUg3Sd",
                "url" => "https://www.instagram.com/rsd_cimacan/",
                "img" => "event/20220105112828_Webinar_live_ig_dr_pudyastuti.jpg",
                "start_date" => "2021-12-09",
                "end_date" => "2021-12-09",
                "start_time" => "13:00:00",
                "end_time" => "14:00:00",
                "location" => "",
                "status" => "publish",
                "create_date" => "2022-01-05 11:28:28",
                "update_date" => "2022-01-05 11:28:28",
            ),
            array(
                "id" => 9,
                "title" => "Vaksinasi Desember Minggu 1",
                "sub_desc" => "",
                "description" => "Info Vaksinasi COVID-19 di RSUD Cimacan sudah hadir lagi nih!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 6 hingga 10 Desember 2021.<br /><br />Kami menyediakan Vaksin jenis Pfizer dan Sinovac untuk dosis 2 serta Vaksin Astrazeneca untuk dosis 1 dan 2. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan juga diharapkan membawa alat tulis (ballpaint).<br /><br />Yuk kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa<br />Pendaftaran vaksinasi dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105113053_vaksinasi_desember_1.jpg",
                "start_date" => "2021-12-06",
                "end_date" => "2021-12-10",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:30:53",
                "update_date" => "2022-01-05 11:30:53",
            ),
            array(
                "id" => 10,
                "title" => "Vaksinasi November Minggu 5",
                "sub_desc" => "",
                "description" => "Info tentang Vaksinasi COVID-19 yang ditunggu-tunggu sudah hadir nih!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 29 November hingga 3 Desember 2021.<br /><br />RSUD Cimacan menyediakan Vaksin jenis Sinovac untuk dosis 1 serta Vaksin Moderna dan Astrazeneca untuk dosis 1 dan 2. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan juga diharapkan membawa alat tulis (ballpaint).<br /><br />Yuk daftar vaksin di RSUD Cimacan!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa<br />Pendaftaran vaksinasi secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua.",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105114006_vaksinasi_november_4.jpg",
                "start_date" => "2021-11-29",
                "end_date" => "2021-12-03",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:40:06",
                "update_date" => "2022-01-05 11:40:06",
            ),
            array(
                "id" => 11,
                "title" => "Vaksinasi November Minggu 3",
                "sub_desc" => "",
                "description" => "Info tentang Vaksinasi COVID-19 hadir lagi nih!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 15-19 November 2021.<br /><br />Kali ini RSUD Cimacan menyediakan Vaksin jenis Pfizer untuk dosis 1 dan 2 serta Vaksin Sinovac dan Astrazeneca untuk dosis ke-2. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan juga diharapkan membawa alat tulis (ballpaint).<br /><br />Yuk! Jangan sampai ketinggalan kesempatan vaksin kali ini yaa<br />Jangan lupa pendaftaran vaksinasi secara online melalui aplikasi Tartimah!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105114506_vaksinasi_november_3.jpg",
                "start_date" => "2021-11-15",
                "end_date" => "2021-11-19",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:45:06",
                "update_date" => "2022-01-05 11:45:06",
            ),
            array(
                "id" => 12,
                "title" => "Donor Darah Bulan November",
                "sub_desc" => "",
                "description" => "Mincan mau kasih info tentang donor darah nih!<br /><br />RSUD Cimacan akan mengadakan Kegiatan Donor Darah yang akan dilaksanakan pada:<br /><br />Hari: Senin, 15 November 2021<br />Lokasi: Taman Kering IGD PONEK RSUD Cimacan<br />Waktu: Pk 09.00 hingga selesai<br /><br />Sahabat Cimacan tidak perlu takut karena donor darah akan dilakukan sesuai dengan protokol kesehatan.<br />Jangan lupa untuk para calon pendonor, ada beberapa syarat donor darah yang harus diperhatikan yaa.<br />Yuk, donor darah! Setiap tetes darah yang kalian berikan bisa memberi banyak harapan bagi mereka yang membutuhkan.",
                "category" => "8jAiIJCtZguS20hROyENBsGU",
                "url" => "",
                "img" => "event/20220105114731_donor_darah_november.jpg",
                "start_date" => "2021-11-15",
                "end_date" => "2021-11-15",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:47:31",
                "update_date" => "2022-01-05 11:47:31",
            ),
            array(
                "id" => 13,
                "title" => "Vaksinasi November Minggu 2",
                "sub_desc" => "",
                "description" => "Siapa yang lagi nunggu kabar vaksin nih?<br />Mincan mau kasih info terbaru lagi nih tentang vaksin COVID-19!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 8-12 November 2021.<br /><br />Kali ini RSUD Cimacan menyediakan Vaksin jenis Pfizer untuk dosis 1 dan 2 serta Vaksin Sinovac dan Astrazeneca untuk dosis ke-2. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan juga diharapkan membawa alat tulis (ballpaint).<br /><br />Yuk! Jangan sampai ketinggalan yaa<br />Jangan lupa pendaftaran vaksinasi secara online melalui aplikasi Tartimah!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105115344_vaksinasi_november_2.jpg",
                "start_date" => "2021-11-08",
                "end_date" => "2021-11-12",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:53:44",
                "update_date" => "2022-01-05 11:53:44",
            ),
            array(
                "id" => 15,
                "title" => "Vaksinasi November Minggu 1",
                "sub_desc" => "",
                "description" => "Info vaksinasi COVID-19 di RSUD Cimacan kembali hadir nih!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin sampai Jumat, 1-5 November 2021.<br /><br />Vaksinasi diutamakan untuk penerima dosis 1 yaa. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan diharapkan untuk membawa alat tulis (ballpaint).<br /><br />Kuota vaksinasi terbatas hanya untuk 1000 orang per hari.<br /><br />Jangan lupa pendaftaran vaksinasi secara online melalui aplikasi Tartimah yaa",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105115912_vaksinasi_november_1.jpg",
                "start_date" => "2021-11-01",
                "end_date" => "2021-11-05",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 11:59:12",
                "update_date" => "2022-01-05 11:59:12",
            ),
            array(
                "id" => 16,
                "title" => "Vaksinasi November Minggu 4",
                "sub_desc" => "",
                "description" => "Mincan mau berbagi info tentang Vaksinasi COVID-19 yang ditunggu-tunggu nih!<br /><br />RSUD Cimacan membuka pelayanan vaksinasi COVID-19 untuk masyarakat umum pada hari Senin-Jumat, 22-26 November 2021.<br /><br />RSUD Cimacan menyediakan Vaksin jenis Pfizer dan Sinovac untuk dosis 1 dan 2 serta Vaksin Astrazeneca untuk dosis ke-2. Vaksinasi akan dilakukan di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 09.00 sampai 15.00.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk Anak dan juga diharapkan membawa alat tulis (ballpaint).<br /><br />Yuk daftar vaksin di RSUD Cimacan! Jangan sampai ketinggalan kesempatan vaksin kali ini yaa.<br />Pendaftaran vaksinasi secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua.",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220105141108_vaksinasi_november_4_fix.jpg",
                "start_date" => "2021-11-22",
                "end_date" => "2021-11-26",
                "start_time" => "09:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-05 14:11:08",
                "update_date" => "2022-01-05 14:11:08",
            ),
            array(
                "id" => 19,
                "title" => "Vaksinasi Januari Minggu 2",
                "sub_desc" => "",
                "description" => "RSUD Cimacan saat ini membuka pelayanan Vaksinasi COVID-19 untuk masyarakat umum mulai dari usia 7 tahun ke atas loh!<br /><br />Vaksinasi Covid-19 dilakukan pada hari Senin-Jumat, 10 sampai 14 Januari 2022 di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 13.00 sampai 15.00.<br /><br />Kami menyediakan Vaksin jenis Sinovac untuk dosis 1 dan 2.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, dan membawa alat tulis pribadi (ballpaint).<br /><br />Yuk Sahabat Cimacan vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah. Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220110092025_vaksinasi_januari_2.jpg",
                "start_date" => "2022-01-10",
                "end_date" => "2022-01-14",
                "start_time" => "13:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-10 09:20:25",
                "update_date" => "2022-01-10 09:20:25",
            ),
            array(
                "id" => 21,
                "title" => "Vaksin Bulan Januari Minggu 3",
                "sub_desc" => "",
                "description" => "RSD Cimacan saat ini sudah membuka pelayanan Vaksinasi COVID-19 untuk masyarakat umum mulai dari usia 7 tahun ke atas!<br /><br />Vaksinasi Covid-19 dilakukan pada hari Senin-Jumat, 17 sampai 21 Januari 2022 di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 13.00 sampai 15.00.<br /><br />Kami menyediakan Vaksin jenis Sinovac untuk dosis 1 dan 2 serta jenis Pfizer untuk dosis 2.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, dan membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220117082017_271953136_1230308974162300_7056465776181016807_n.jpg",
                "start_date" => "2022-01-17",
                "end_date" => "2022-01-21",
                "start_time" => "13:00:00",
                "end_time" => "15:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-17 08:20:17",
                "update_date" => "2022-01-17 08:20:17",
            ),
            array(
                "id" => 22,
                "title" => "Vaksin Bulan Januari Minggu 4",
                "sub_desc" => "",
                "description" => "RSD Cimacan saat ini sudah membuka pelayanan Booster Vaksinasi COVID-19 untuk masyarakat umum!<br /><br />Vaksinasi Covid-19 dilakukan pada hari Senin-Jumat, 24 sampai 28 Januari 2022 di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 10.00 sampai 13.00.<br /><br />Kami menyediakan Vaksin jenis Sinovac untuk dosis 1, 2, dan 3 (booster) serta jenis Pfizer untuk dosis 2 dan 3 (booster).<br />Syarat vaksin booster: usia &ge;18 tahun, 6 bulan rentang waktu dari dosis ke-2, dan sudah memiliki e-ticket pada aplikasi Peduli Lindungi.<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220123162815_vaksinasi_januari_4.jpg",
                "start_date" => "2022-01-24",
                "end_date" => "2022-01-28",
                "start_time" => "10:00:00",
                "end_time" => "13:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-23 16:28:15",
                "update_date" => "2022-01-23 16:28:15",
            ),
            array(
                "id" => 23,
                "title" => "Vaksinasi Februari Minggu 1",
                "sub_desc" => "",
                "description" => "RSUD Cimacan saat ini sudah membuka pelayanan Booster Vaksinasi COVID-19 untuk masyarakat umum!<br /><br />Vaksinasi Covid-19 dilakukan pada hari Senin, Rabu-Jumat, 31 Januari dan 2-4 Februari 2022 di Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK) dari pukul 10.00 sampai 13.00.<br /><br />Kami menyediakan Vaksin jenis Sinovac untuk dosis 1 dan 2 serta jenis Pfizer, Moderna, dan Astrazeneca untuk dosis 2 dan 3 (booster).<br /><br />Ada beberapa syarat untuk vaksin booster nih Sahabat Cimacan, yaitu:<br />- Usia &ge;18 tahun<br />- 6 bulan rentang waktu dari dosis ke-2<br />- Memiliki e-ticket vaksin booster pada aplikasi Peduli Lindungi<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220130112229_vaksin-februari-minggu-1.jpg",
                "start_date" => "2022-01-31",
                "end_date" => "2022-02-04",
                "start_time" => "10:00:00",
                "end_time" => "13:00:00",
                "location" => "Aula Vaksin, Gedung Lama RSUD Cimacan (Sebelah PONEK)",
                "status" => "publish",
                "create_date" => "2022-01-30 11:22:29",
                "update_date" => "2022-01-30 11:22:29",
            ),
            array(
                "id" => 24,
                "title" => "Vaksin Sinovac RSUD Cimacan",
                "sub_desc" => "",
                "description" => "RSUD Cimacan kini kembali menghadirkan Vaksinasi Covid-19 melalui Poli khusus Vaksin Covid yang akan buka pada:<br /><br />- Hari:<br />Senin, Rabu, &amp; Sabtu<br />- Tempat:<br />Ruang Tunggu Poli Jiwa (Senin &amp; Rabu)<br />Poli MCU (Sabtu)<br />- Waktu:<br />09.00 hingga 12.00 WIB<br />- Jenis Vaksin:<br />Sinovac (usia 6 hingga 11 tahun, dosis 2 &amp; 3)<br /><br />Ada beberapa syarat untuk vaksin booster nih Sahabat Cimacan, yaitu:<br />- Usia &ge;18 tahun<br />- 6 bulan rentang waktu dari dosis ke-2<br />- Memiliki e-ticket vaksin booster pada aplikasi Peduli Lindungi<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220511062322_Vaksin-covid-Sinovac-Ruang-Baru-April.jpg",
                "start_date" => "2022-04-01",
                "end_date" => "2022-05-31",
                "start_time" => "09:00:00",
                "end_time" => "12:00:00",
                "location" => "Sesuai deskripsi event",
                "status" => "publish",
                "create_date" => "2022-05-11 06:23:22",
                "update_date" => "2022-05-11 06:23:22",
            ),
            array(
                "id" => 25,
                "title" => "Vaksin Pfizer RSUD Cimacan",
                "sub_desc" => "",
                "description" => "RSUD Cimacan kini kembali menghadirkan Vaksinasi Covid-19 melalui Poli khusus Vaksin Covid yang akan buka pada:<br /><br />- Hari:<br />Senin, Rabu, &amp; Sabtu<br />- Tempat:<br />Ruang Tunggu Poli Jiwa (Senin &amp; Rabu)<br />Poli MCU (Sabtu)<br />- Waktu:<br />09.00 hingga 12.00 WIB<br />- Jenis Vaksin:<br />Pfizer (usia &ge;12 tahun, dosis 1,2,3)<br /><br />Ada beberapa syarat untuk vaksin booster nih Sahabat Cimacan, yaitu:<br />- Usia &ge;18 tahun<br />- 6 bulan rentang waktu dari dosis ke-2<br />- Memiliki e-ticket vaksin booster pada aplikasi Peduli Lindungi<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa. Vaksinasinya gratis.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220511062450_Vaksin-covid-Pfizer-Ruang-Baru-April.jpg",
                "start_date" => "2022-04-01",
                "end_date" => "2022-05-31",
                "start_time" => "09:00:00",
                "end_time" => "12:00:00",
                "location" => "Sesuai deskripsi event",
                "status" => "publish",
                "create_date" => "2022-05-11 06:24:50",
                "update_date" => "2022-05-11 06:24:50",
            ),
            array(
                "id" => 26,
                "title" => "Update Vaksinasi Bulan Juni",
                "sub_desc" => "",
                "description" => "Mincan mau menginfokan kembali nih terkait vaksinasi covid-19 di RSUD Cimacan!<br /><br />RSUD Cimacan menghadirkan Layanan Vaksinasi Covid-19 melalui Poli khusus Vaksin Covid yang akan buka pada:<br /><br />Hari:<br />Senin, Rabu, &amp; Sabtu<br /><br />Tempat:<br />Ruang Tunggu Poli Jiwa (Senin &amp; Rabu)<br />Poli MCU (Sabtu)<br /><br />Waktu:<br />09.00 hingga 12.00 WIB<br /><br />Jenis Vaksin:<br />Pfizer (usia &ge;12 tahun, dosis 1,2,3)<br /><br />Ada beberapa syarat untuk vaksin booster nih Sahabat Cimacan, yaitu:<br />- Usia &ge;18 tahun<br />- 6 bulan rentang waktu dari dosis ke-2<br />- Memiliki e-ticket vaksin booster pada aplikasi Peduli Lindungi<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220617105743_vaksin-update-bulan-juni.jpg",
                "start_date" => "2022-06-01",
                "end_date" => "2022-06-30",
                "start_time" => "09:00:00",
                "end_time" => "12:00:00",
                "location" => "Sesuai deskripsi event",
                "status" => "publish",
                "create_date" => "2022-06-17 10:57:43",
                "update_date" => "2022-06-17 10:57:43",
            ),
            array(
                "id" => 28,
                "title" => "UPDATE VAKSINASI JULI",
                "sub_desc" => "",
                "description" => "Halo Sahabat Cimacan..&nbsp;<br />Info Vaksinasi Covid-19 yang ditunggu-tunggu sudah hadir kembali nih!&nbsp;<br /><br />RSUD Cimacan menghadirkan Layanan Vaksinasi Covid-19 melalui Poli khusus Vaksin Covid yang akan buka pada:<br /><br />Hari:&nbsp;<br />Senin, Rabu, &amp; Sabtu<br /><br />Tempat:&nbsp;<br />Ruang Tunggu Poli Jiwa (Senin &amp; Rabu)&nbsp;<br />Poli MCU (Sabtu)<br /><br />Waktu:<br />09.00 hingga 12.00 WIB<br /><br />Jenis Vaksin:<br />Sinovac (Dosis 1 usia 6-11 tahun &amp; Dosis 2,3)<br />Moderna (Dosis 1,2,3)&nbsp;<br /><br />Ada beberapa syarat untuk vaksin booster nih Sahabat Cimacan, yaitu:&nbsp;<br />- Usia &ge;18 tahun<br />- 6 bulan rentang waktu dari dosis ke-2<br />- Memiliki e-ticket vaksin booster pada aplikasi Peduli Lindungi<br /><br />Setiap peserta vaksin diharapkan untuk membawa KTP atau Kartu Keluarga untuk peserta vaksinasi Anak, serta membawa alat tulis pribadi (ballpaint).<br /><br />Yuk, Sahabat Cimacan kita vaksin!&nbsp;<br />Jangan sampai ketinggalan daftar vaksin kali ini yaa.&nbsp;<br /><br />Pendaftaran dapat dilakukan secara online melalui aplikasi Tartimah.&nbsp;<br />Download dan install aplikasi Tartimah dari Google Play Store Sahabat Cimacan semua!",
                "category" => "JR6IHimr5n12dajWtZfsuBLX",
                "url" => "",
                "img" => "event/20220708083316_WhatsApp-Image-2022-07-06-at-5.20.28-PM.jpeg",
                "start_date" => "2022-07-01",
                "end_date" => "2022-07-31",
                "start_time" => "09:00:00",
                "end_time" => "12:00:00",
                "location" => "Gedung B Rawat Jalan Lantai 1",
                "status" => "publish",
                "create_date" => "2022-07-08 08:33:16",
                "update_date" => "2022-07-08 08:33:16",
            ),
            array(
                "id" => 29,
                "title" => "Kidney Health For All",
                "sub_desc" => "",
                "description" => "Selamat Hari Ginjal Dunia, 9 Maret 2023<br />\"Kidney Health For All, Preparing For The Unexpected , Supporting The Vulnerable\"<br /><br />Mari sehatkan ginjal kita Sobat Cimacan, salah satunya dengan rutin minum air putih setiap hari.<br /><br />Dan jangan lupa untuk mengikuti seminar kesehatan \"Dampak Penurunan Fungsi Ginjal pada Kesehatan Sehari-hari\"<br /><br />Bersama Dokter Spesialis Penyakit Dalam RSUD Cimacan, dr Panji Gugah Bhaskara, Sp. PD, FINASIM, di moderatori oleh dr. Afif Imanfadanu. Bertempat di Ruang Instalasi Hemodialisa RSUD Cimacan, hari Kamis, 16 Maret 2023.<br /><br />Ginjal Sehat Untuk Semua.",
                "category" => "EcP6WsMO5hq7aHje1YoUg3Sd",
                "url" => "",
                "img" => "event/20230330083349_334315170_142554055113105_3853250427601649276_n.jpg",
                "start_date" => "2023-03-16",
                "end_date" => "2023-03-16",
                "start_time" => "12:30:00",
                "end_time" => "14:00:00",
                "location" => "Rsud Cimacan",
                "status" => "publish",
                "create_date" => "2023-03-09 08:33:49",
                "update_date" => "2023-03-30 08:33:49",
            ),
            array(
                "id" => 30,
                "title" => "Kapan saja asupan insulin yang tepat untuk anak saat bulan puasa",
                "sub_desc" => "",
                "description" => "Ramadhan tiba Ramadhan tiba!!!<br /><br />Gimana ya cara ajarkan berpuasa pada anak pengidap diabetes?<br /><br />bagaimana ya cara kontrol gula darah nya?<br /><br />Kapan saja asupan insulin yang tepat untuk anak saat bulan puasa?<br /><br />Mari kita kupas tuntas bersama dokter-dokter spesialis anak RSUD Cimacan, dr. Andri Saputra, Sp.A mengusung tema Keamanan Berpuasa dan Pemantauan Gula Darah saat Ramadhan Pada Anak.<br /><br />serta dr. Yonita Aprilia, Sp.A yang akan membawakan tema Pemberian Insulin dan Aktivita Fisis Selama Berpuasa Pada D M Tipe-1.<br /><br />Jangan lewatkan Live Instagram nya pada hari Senin, 20 Maret 2023. Pukul 14.00-selesai.<br /><br />Yuk simak dan segera siapkan pertanyaannya ya Sobat Cimacan, kapan lagi pertanyaannya dijawab langsung oleh dokter-dokter spesialis anak langsung lho!",
                "category" => "EcP6WsMO5hq7aHje1YoUg3Sd",
                "url" => "",
                "img" => "event/20230330084205_335991035_158847453709610_8095902891809373324_n.jpg",
                "start_date" => "2023-03-20",
                "end_date" => "2023-03-20",
                "start_time" => "14:00:00",
                "end_time" => "16:00:00",
                "location" => "Rsud Cimacan",
                "status" => "publish",
                "create_date" => "2023-03-19 08:42:05",
                "update_date" => "2023-03-30 08:42:05",
            ),
            array(
                "id" => 31,
                "title" => "gangguan pendengaran akibat bising",
                "sub_desc" => "Sobat Cimacan, Yuk sharing lagi di Live IGÂ @RSUD.Cimacan\r\n\r\nEdukasi kali ini akan membahas tentang gangguan pendengaran akibat bising bersama Dokter Spesialis Penyakit Telinga Hidung Tenggorok Bedah Kep",
                "description" => "Sobat Cimacan, Yuk sharing lagi di Live IG&nbsp;<a class=\"x1i10hfl xjbqb8w x6umtig x1b1mbwd xaqea5y xav7gou x9f619 x1ypdohk xt0psk2 xe8uvvx xdj266r x11i5rnm xat24cr x1mh8g0r xexx8yu x4uap5 x18d9i69 xkhd6sd x16tdsg8 x1hl2dhg xggy1nq x1a2a7pz notranslate _a6hd\" tabindex=\"0\" role=\"link\" href=\"https://www.instagram.com/RSUD.Cimacan/\">@RSUD.Cimacan</a><br /><br />Edukasi kali ini akan membahas tentang gangguan pendengaran akibat bising bersama Dokter Spesialis Penyakit Telinga Hidung Tenggorok Bedah Kepala dan Leher, dr. Pudyastuti Rachyanti, Sp. THT-KL.<br /><br />Sobat semua dapat interaktif bertanya atau menceritakan pengalamannya di kolom komentar yang nantinya acara ini akan dipandu oleh drg. Hariansyah Buana Putra.<br /><br />Save The Date Sobat Cimacan!",
                "category" => "EcP6WsMO5hq7aHje1YoUg3Sd",
                "url" => "",
                "img" => "event/20230330095827_337571048_1901702160181638_1964101280929044323_n.jpg",
                "start_date" => "2023-03-28",
                "end_date" => "2023-03-28",
                "start_time" => "14:00:00",
                "end_time" => "15:00:00",
                "location" => "Rsud Cimacan",
                "status" => "publish",
                "create_date" => "2023-03-28 09:58:27",
                "update_date" => "2023-03-30 09:58:27",
            ),
            array(
                "id" => 32,
                "title" => "Jangan Lewatkan Live Instagram CIMAOS",
                "sub_desc" => "",
                "description" => "Jangan Lewatkan Live Instagram CIMAOS (Cimacan Obrol Santai)<br /><br />Bersama dr. Wulan Nurmala, Sp. OG kita akan membahas mengenai ibu hamil yang hendak menjalankan ibadah puasa, tetapi ragu dengan kesehatan si buah hati.<br /><br />Jika sobat mengalami hal yang sama, yuk kita sharing pada hari, Kamis 30 Maret 2023 hanya di Instagram resmi RSUD Cimacan.",
                "category" => "EcP6WsMO5hq7aHje1YoUg3Sd",
                "url" => "",
                "img" => "event/20230330100019_338590988_578271344270889_6505083556536826197_n.jpg",
                "start_date" => "2023-03-30",
                "end_date" => "2023-03-30",
                "start_time" => "14:00:00",
                "end_time" => "16:00:00",
                "location" => "Rsud Cimacan",
                "status" => "publish",
                "create_date" => "2023-03-30 10:00:19",
                "update_date" => "2023-03-30 10:00:19",
            ),
        );

        $event_categories = EventCategory::get();

        // Log::info($event_categories->where('name', 'Kesehatan Anak')->first());
        $donorDarah = $event_categories->where('name', 'Donor Darah')->first();
        $webinar = $event_categories->where('name', 'Webinar')->first();
        $vaksinasi = $event_categories->where('name', 'Vaksinasi')->first();
        
        $payloadEvent = [];
        foreach ($t_event as $key => $value) {
            if($value['category'] == '8jAiIJCtZguS20hROyENBsGU'){
                // Donor Darah
                $event_category_id = $donorDarah->id;
            } else if($value['category'] == 'EcP6WsMO5hq7aHje1YoUg3Sd'){
                // Webinar
                $event_category_id = $webinar->id;
            } else {
                // Vaksinasi
                $event_category_id = $vaksinasi->id;
            }

            // kalo ada kolom status
            // if($value['status'] == 'publish'){
            //     $status = 1;
            // } else {
            //     $status = 0;
            // }

            $payloadEvent[] = [
                'title' => $value['title'],
                'slug' => str_replace(' ', '-', strtolower($value['title'])) . '-' . $this->generateRandomString(5),
                'sub_desc' => $value['sub_desc'] == '' ? null : $value['sub_desc'],
                'description' => $value['description'],
                'event_category_id' => $event_category_id,
                'url' => $value['url'] == '' ? null : $value['url'],
                'img' => str_replace('event/', 'events/', $value['img']),
                'start_date' => $value['start_date'],
                'end_date' => $value['end_date'],
                'start_time' => $value['start_time'],
                'end_time' => $value['end_time'],
                'location' => $value['location'] == '' ? null : $value['location'],
                // 'status' => $status,
                'created_at' => now(),
                'updated_at' => now()
            ];
        }

        DB::table('events')->insert($payloadEvent);
    }
}
